### ISSUE TITLE
We use railsconfig for environment configuration in rails apps

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#23]
See #5, #6.

**Comment by darrenleeweber** [comment]
:-1: because this imposes too much restriction on one particular approach to configuration.  For example, an alternative is to use a combination of system ENV variables and ruby configuration blocks; e.g. the sdr-services-app is a legacy sinatra project that was adapted to work with a DB, see
  - https://github.com/sul-dlss/sdr-services-app
  - https://github.com/sul-dlss/sdr-services-app/blob/master/config/boot.rb
  - https://github.com/sul-dlss/sdr-configs/blob/master/sdr-services-app/config/database.yml
  - https://github.com/sul-dlss/sdr-configs/tree/master/sdr-services-app/config/environments
  - https://github.com/sul-dlss/sdr-configs/blob/master/sdr-services-app/config/environments/staging.rb#L2
  - https://github.com/sul-dlss/sdr-configs/blob/master/sdr-services-app/config/deploy/staging.rb#L3-L7
  - https://github.com/sul-dlss/sdr-services-app/blob/master/config/deploy/server_settings.rb#L10-L16

Also, using ENV values is reasonable in the context of a gem project.  Here's a concrete example of using ENV to configure a gem. See

    https://github.com/sul-dlss/triannon-client#configuration
    https://github.com/sul-dlss/triannon-client/blob/master/lib/triannon-client.rb#L1-L2
    https://github.com/sul-dlss/triannon-client/blob/master/lib/triannon-client/configuration.rb

The default values are defined in ruby in lib/triannon-client/configuration.rb but they can be modified in several ways, including ENV values set on the system, ENV values set in a shell, ENV values set on a command line, and then attribute setters on the config object. This is a very flexible system.

**Comment by ndushay** [comment]
:-1:   Maybe I'm being stupid, but I don't know what you mean by "railsconfig", @azaroth42.   I might need an example, in which case maybe this should be a PR so I can comment by the line and see how it fits into the playbook overall.

I'm guessing I agree with the sentiment, but I'm not sure what you're actually proposing here.

**Comment by mejackreed** [comment]
Naomi, rails_config is a gem that is used for configuring Rails applications (https://github.com/railsconfig/rails_config). It is used currently in :

 - SearchWorks
 - EarthWorks
 - embed
 - GeoBlacklight
 - GeoMonitor

@cbeer has a good comment here: https://github.com/sul-dlss/DeveloperPlaybook/issues/5#issuecomment-92425645 
which talks about the flexibility of integrating with ENV vars

**Comment by ndushay** [comment]
@mejackreed thanks for that.

**Comment by cbeer** [comment]
+0. I'm not sure using `rails_config` is a community practice yet, although many recent projects have adopted it. If some of our other rails projects (or non-rails, even) adopted it (thinking purl, argo, the stanford sync work, hydrus, revs) or their project teams were committed to using it, I could be persuaded to change that to :+1:.

**Comment by azaroth42** [comment]
Withdrawn!
