### ISSUE TITLE
Ensure implicated people are informed

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/DeveloperPlaybook#35]
When submitting an Issue or PR for the playbook, if there are people we would either like reactions from or are somehow implicated in the outcome, then we should seek their input.  One way to do this in github is to @ tag them in the description or a comment, or simply to ping them on IM or by other means.  This would reduce the requirement for their constant attention on the list of issues, while ensuring that everyone has the opportunity to weigh in on things that affect them.

It is encouraged that people actively acknowledge issues that they have read with +1 (I would defend this to another member of a team) ; +0 (I can live with this) ; -0 (I guess I can live with this) or -1 (I really have trouble with this).

**Comment by darrenleeweber** [comment]
:+1: as discussed, thanks

**Comment by azaroth42** [comment]
(e.g.) @eefahy ?

**Comment by cbeer** [comment]
Is this in the context of the playbook, or in our general work?

**Comment by azaroth42** [comment]
Sorry, for the playbook in particular.  Will clarify in the issue text. But seems like a good practice in general?

**Comment by cbeer** [comment]
Maybe it's just me, but it seem obvious (and not worth recording here) that when you expect something from someone, you should tell them about it by any means necessary. I don't see a big risk to the our projects if you do it via github or email or otherwise (although, I think github is a great place for that and tagging teams e.g. @sul-dlss/devops is something we're already suggesting where appropriate)

I'm not sure how this addresses the concern "that only the active few are making decisions that affect the many", unless you're suggesting we tag every developer on every proposal (in which case, I'd ask, what's the point?) Maybe a better process would be to: a) strongly encourage people to acknowledge proposals with a -0/+0 if they don't care, and b) send a weekly summary of opened and closed issues for people who want to ignore github notitces.

**Comment by azaroth42** [comment]
I completely agree (it would be hard not to :) ) with the first part. Will revise to using @ tags as a suggested method to alert people rather than recommended or mandatory. The intent is to alert people beyond the regular set of automated tools which are easy to ignore that they should pay attention to a particular issue. Does that address the concern?

For the second part, the thought was that if there are ways to ping people for their attention on a particular issue that we think they should weigh in on, then we're reducing their work load at a minimal expense to the submitter or commenter.  For example, Gary was proactive in giving the thumbs up for the bootstrap proposal (and thank you for that!) but it would be nice to hear from other folks that work on the front end side of things on that issue too.  On the flip side, I bet that Gary doesn't care at all about some of the issues and pushing people to +0 things (per a) seems like it fails the "don't block on non-response" test.

I do definitely agree with (b) though.  @eefahy and I have discussed a better structure for meetings, which would start with walking through the issues that are pending approval. We could also send them out in email, and have more than one person responsible for doing that summarization to ensure that it happens with some dependability.

**Comment by azaroth42** [comment]
[Updated description to address @cbeer's concerns, I hope]

**Comment by cbeer** [comment]
> there are ways to ping people for their attention on a particular issue that we think they should weigh in on

My concern there is knowing who to ping (or, who would be offended not to get pinged). I'd rather bake in an assumption that the playbook is a useful resource that people will gladly refer to at least once a week and take time to chime in and provide feedback. Asking people to acknowledge they've read something that they can live with doesn't seem like much of a burden.

If the concern is just noise, I think a weekly digest/reminder to dlss-developers would be sufficient without  too much overhead.

**Comment by azaroth42** [comment]
I hope that no one would be offended if they're not pinged :) 

Perhaps we should seek the feedback of people who haven't been participating to date to see what would help them, or if they're happy to just go with whatever is discussed and decided.  (Heh, ask your users, novel concept, I know ...)

**Comment by cbeer** [comment]
:+1:  to asking people. Do you want to tag everyone in DLSS on this ticket?

> I hope that no one would be offended if they're not pinged :)

I think that's a very big risk. If I'm counting on you to ping me about something relevant to me (and, hopefully, everything in this playbook is relevant to all developers, and, in fact, everyone in the department) and you don't, I think a not-entirely-unreasonable assumption is you intentionally chose not to ping me. Putting the burden on the reader, not the author, seem much more kind to the author.

**Comment by azaroth42** [comment]
Touche!

> Putting the burden on the reader, not the author, seem much more kind to the author.
The author who is, after all, doing the work.

I'm going to move the issue to To Discuss, so we come back to it to figure out how to ensure inclusion without getting in the way.

**Comment by darrenleeweber** [comment]
I want to add a note about some of the F2F discussion on this topic.  The issue is 'inclusive' consensus in the context of the rules for acceptance; that is, the playbook content, in some cases, may only require 4 +1's (given <= 1x -1) to pass within any given week.  If DLSS folks are away at a conference or on vacation (however their focus will be elsewhere), it's possible that significant proposals could pass without their input.  Or, a proposal may be created by a DLSS group as a result of a small group discussion (e.g., managers come up with a bright idea) and the proposal might require wider review from various groups - this is about tagging DLSS group lists, such as developers, dev-ops, or sys-admins for their perspectives on any proposal where they were not immediately involved in discussing or creating the proposal in the first instance.

**Comment by cbeer** [comment]
Bulk closing inactive issues. Feel free to reopen as needed.

**Comment by darrenleeweber** [comment]
Ah, I'm not sure we have closure on this issue.  Perhaps it could be a topic for discussion at a meeting?

**Comment by mjgiarlo** [comment]
Should this still be open? @darrenleeweber @cbeer @azaroth42

**Comment by azaroth42** [comment]
Close at will, no need for formalizing a process if synchronous discussion is working

**Comment by darrenleeweber** [comment]
Close.
